### ISSUE TITLE
Update documentation for these editors

### ISSUE THREAD

**Issue by russmiles** [atomist-rugs/spring-boot-editors#2]
See example in https://github.com/atomist-rugs/common-editors for comparison.

**Comment by ddgenome** [comment]
@russmiles Looking good! Just a few things still need to be done:

-   Should probably depend on rug 0.6.0 since that is now the latest
-   Update the copyright to `Copyright © 2016 Atomist, Inc.`
-   Every param needs the full complement of annotations
-   Most other tests indent the `and` two more spaces https://github.com/atomist-rugs/spring-boot-editors/blob/master/.atomist/tests/AddDockerMavenBuild.rt#L113-L117 https://github.com/atomist-rugs/spring-boot-editors/blob/master/.atomist/tests/UpdateServicePort.rt#L55-L56
-   The description in the README should probably be made more specific to this repo https://github.com/atomist-rugs/spring-boot-editors/blame/master/README.md#L5-L7

**Comment by ddgenome** [comment]
Also, CHANGELOG
